---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - ingress
  verbs:
  - create
  - delete
  - get
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - pod
  verbs:
  - create
  - delete
  - get
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - update
  - watch
- apiGroups:
  - home-assistant.lmatfy.io
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - home-assistant.lmatfy.io
  resources:
  - instances/finalizers
  verbs:
  - update
- apiGroups:
  - home-assistant.lmatfy.io
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
