name: Testing
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/checkout@v4
      - run: make test

      - run: go install github.com/t-yuki/gocover-cobertura@latest
        if: github.event_name == 'pull_request'
      - run: gocover-cobertura < cover.out > cover.xml
        if: github.event_name == 'pull_request'
      - uses: irongut/CodeCoverageSummary@v1.3.0
        if: github.event_name == 'pull_request'
        with:
          filename: cover.xml
          badge: false
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - uses: ncruces/go-coverage-report@v0
        if: github.ref == 'refs/heads/main'
        with:
          report: true
          chart: false
          amend: true
          coverage-file: cover.out

  e2e-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: engineerd/setup-kind@v0.5.0
        with:
          wait: 30s
          version: v0.11.1
          image: kindest/node:v1.20.7

      - uses: actions/setup-go@v5
      - name: Install Operator SDK
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.36.1/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64
          mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

      - run: make test-e2e
